export const exampleMeshGrates: Grate[] = [
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 999.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21610',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 999.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21615',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 999.5,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21620',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 999.5,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21625',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 499.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21710',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 499.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21715',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 499.5,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21720',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 499.5,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21725',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 999.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21810',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 999.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21815',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 999.5,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21820',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 999.5,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21825',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 499.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21910',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 499.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21915',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 499.5,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21920',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 499.5,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '21925',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 999.5,
    width: 198,
    height: 30,
    surfaces: 'antislip',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '25x2',
    meshSize: '21x21',
    surfaceTreatment: 'Passivated',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304358',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 499.5,
    width: 198,
    height: 30,
    surfaces: 'antislip',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '25x2',
    meshSize: '21x21',
    surfaceTreatment: 'Passivated',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304359',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 299,
    width: 198,
    height: 30,
    surfaces: 'antislip',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '25x2',
    meshSize: '21x21',
    surfaceTreatment: 'Passivated',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304360',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 999.5,
    width: 198,
    height: 30,
    surfaces: 'antislip',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '25x2',
    meshSize: '21x21',
    surfaceTreatment: 'Passivated',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304361',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 499.5,
    width: 198,
    height: 30,
    surfaces: 'antislip',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '25x2',
    meshSize: '21x21',
    surfaceTreatment: 'Passivated',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304362',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 299,
    width: 198,
    height: 30,
    surfaces: 'antislip',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '25x2',
    meshSize: '21x21',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304363',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 999.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '21x21',
    surfaceTreatment: 'Passivated',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304364',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 499.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '21x21',
    surfaceTreatment: 'Passivated',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304365',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 374,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '21x21',
    surfaceTreatment: 'Passivated',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304366',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 999.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '21x21',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304367',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 499.5,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '21x21',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304368',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 374,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '21x21',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '304369',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 374,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414130',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 374,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414131',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 374,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414132',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 374,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414133',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 299,
    width: 198,
    height: 30,
    surfaces: 'antislip',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '30x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414140',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 299,
    width: 198,
    height: 30,
    surfaces: 'plain',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '30x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414141',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 374,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414180',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 374,
    width: 123,
    height: 20,
    surfaces: 'antislip',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414181',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 374,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x2',
    frameBar: '20x2',
    loadBar: '20x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414182',
  },
  {
    wo: 155,
    wi: 125,
    type: 'mesh',
    lc: 'C250',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 374,
    width: 123,
    height: 20,
    surfaces: 'plain',
    e: 20.5,
    fillingBar: '9,8x3',
    frameBar: '20x3',
    loadBar: '30x3',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414183',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 299,
    width: 198,
    height: 30,
    surfaces: 'antislip',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '30x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414190',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'A15',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 299,
    width: 198,
    height: 30,
    surfaces: 'plain',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '30x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '414191',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 499.5,
    width: 198,
    height: 30,
    surfaces: 'antislip',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '30x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '92200',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 304',
    materialEN: '1.4301',
    length: 499.5,
    width: 198,
    height: 30,
    surfaces: 'plain',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '30x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '92207',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 499.5,
    width: 198,
    height: 30,
    surfaces: 'antislip',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '30x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '92250',
  },
  {
    wo: 230,
    wi: 200,
    type: 'mesh',
    lc: 'L15',
    materialAISI: 'AISI 316L',
    materialEN: '1.4404',
    length: 499.5,
    width: 198,
    height: 30,
    surfaces: 'plain',
    e: 30.5,
    fillingBar: '9,8x2',
    frameBar: '30x2',
    loadBar: '30x2',
    meshSize: '25x25',
    surfaceTreatment: 'Electropolished',
    clearance: null,
    barSpacing: null,
    constructionType: 'old',
    locking: false,
    lockingType: null,
    productNumber: '92257',
  },
];
